### ISSUE TITLE
Warnings and deprecated code

### ISSUE THREAD

**Issue by markNZed** [prosto/neo4j-haystack#3]
I am experimenting with neo4j-haystack and see some concerning messages:

```2024-10-28 18:25:24,878 - neo4j_haystack.document_stores.neo4j_store - WARNING - At the moment nested (complex) objects are not allowed as `list` values in Document object. Property `_split_overlap` will be skipped and not stored in Neo4j node
2024-10-28 18:25:25,428 - neo4j.notifications - WARNING - Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: CALL subquery without a variable scope clause is now deprecated. Use CALL (doc, row) { ... }} {position: line: 7, column: 17, offset: 226} for query: "\n                WITH $records AS batch\n                UNWIND batch as row\n                MERGE (doc:`Document` {id: row.id})\n                SET doc += row{.*, embedding: null}\n                WITH doc, row\n                CALL { WITH doc, row\n                    MATCH(doc:`Document` {id: row.id}) WHERE row.embedding IS NOT NULL\n                    CALL db.create.setNodeVectorProperty(doc, 'embedding', row.embedding)\n                }\n                "```

**Comment by prosto** [comment]
hi @markNZed ,

thanks for reporting this. 

<hr/>

> WARNING - At the moment nested (complex) objects are not allowed as `list` values in Document object. Property `_split_overlap` will be skipped and not stored in Neo4j node

**The above is expected and most probably caused by the `DocumentSplitter` (or `NLTKDocumentSplitter`) component(s) you are using in your experiments. It should not impact you, unless you are using `_split_overlap` metadata property in your code/logic. As per my knowledge it is not used much in Haystack components as well.** See below the explanation.

The issue is how Neo4j actually stores haystack Documents in database. It can not store nested attributes and thus haystack Documents with its metadata attributes are flattened before being saved in Neo4j. Below is an example of a haystack Document and how is is actually represented in Neo4j:

```python
from haystack import Document
document = Document(id="451999", content="A 1916 film directed by Chester M. Franklin.",
    meta={
        "title": "",
        "vote_average": 0.0,
        "genres": ["Drama"],
        "release_date": "1916-02-20",
        "runtime": 50.0,
    }
)

# Document is flattened before being stored in Neo4j
document.to_dict(flatten=True)
```

<table>
<tr><th>Haystack</th><th>Neo4j (Node)</th></tr>
<tr>
<td>
<pre>
{
  "id": "451999",
  "content": "A 1916 film directed by Chester M. Franklin.",
  "dataframe": null,
  "blob": null,
  "score": null,
  "embedding": null,
  "title": "Martha's Vindication",
  "vote_average": 0.0,
  "genres": ["Drama"],
  "release_date": "1916-02-20",
  "runtime": 50.0
}
<pre>
</td>
<td>
<pre>
{
  "identity": 12,
  "labels": ["Document"],
  "properties": {
    "release_date": "1916-02-20",
    "genres": ["Drama"],
    "vote_average": 0.0,
    "runtime": 50.0,
    "id": "451999",
    "title": "Martha's Vindication",
    "content": "A 1916 film directed by Chester M. Franklin."
  },
  "elementId": "4:bd65188c-5b0a-46c5-80ca-2ff365b9899a:12"
}
</pre>
</td>
</tr>
<table>

Please notice the following:

- Haystack Document is flattened before it is stored in Neo4j. 
- Nested dictionaries in the Document's `meta` will be flattened as well (e.g. `{"person": {"name": "Leeloo"}}` will be stored as `person.name: "Leeloo"` in Neo4j, separated by `.`)

However, [Constructed types cannot be stored as properties (with the exception of homogenous lists).](https://neo4j.com/docs/cypher-manual/current/values-and-types/property-structural-constructed/#constructed-types). It means that  `"genres"` list from the example above can be stored in Neo4j as it is a list of simple and homogenous (same type) type - list of strings. **In case we have a list of objects/dictionaries in Document's metadata it will be skipped and you will see the warning similar to what you have reported about `_split_overlap`**

If you are curious how `_split_overlap` works with `DocumentSplitter`, take a look at [this test](https://github.com/deepset-ai/haystack/blob/c7b898994e371e376dd3b7236620eeca05f3f463/test/components/preprocessors/test_document_splitter.py#L197). `_split_overlap` is a list of dictionaries (e.g. `[{"doc_id": "id", "range": (0, 5)}]`) and thus will be reported by `neo4j-haystack` as one to be skipped **as currently its not possible to store such lists in Neo4j**.

Currently there is no simple way to store such "complex" lists, if its critical I could enhance logic to at least provide mechanism to handle it within `neo4j-haystack`. Please let me know if thats the case

<hr/>

> This feature is deprecated and will be removed in future versions.This feature is deprecated and will be removed in future versions.

The above warning depends on Neo4j DB version one is using. Are you using version >= `5.23` ? If so [you should expect such warnings as syntax of variables in `CALL` statement](https://neo4j.com/docs/cypher-manual/current/subqueries/call-subquery/#variable-scope-clause) has changed since `5.23` and it causes the warning to pop up. 

It should not break any functionality but the warning could be annoying... I will work on checking which version of the database `neo4j-haystack` connects to in order to avoid the warning (e.g. use older Cypher syntax [internally](https://github.com/prosto/neo4j-haystack/blob/main/src/neo4j_haystack/client/neo4j_client.py#L399) for older versions). But the purpose is to support older versions of Neo4j that is why you should ignore the warning as of now, until I get rid of it in future releases. 

hope it helps

**Comment by markNZed** [comment]
Hi, I am not using _split_overlap and the warnings are not a big deal for me at the moment.  I am using the most recent neo4j DB. Thanks for the explanations!
